#!/usr/bin/env bash
# ============================================================================
# 一键装 sci-auth（鉴权 + LLM 网关 + 运营后台）到一台干净的 Ubuntu。
#
# 幂等：重复跑不会覆盖已有的 /etc/sci-auth.env 与库，只补齐缺的部分。
#
# 用法：sudo deploy-auth/setup.sh
#      DOMAIN=xxx.duckdns.org sudo -E deploy-auth/setup.sh    # 顺便写 Caddyfile
# ============================================================================
set -euo pipefail
[ "$(id -u)" = "0" ] || { echo "!! 请用 root 跑（sudo）" >&2; exit 1; }

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DATA_DIR=/var/lib/sci-auth
ENV_FILE=/etc/sci-auth.env
NEED_NODE_MAJOR=22

echo "== ① Node（需 ≥$NEED_NODE_MAJOR，node:sqlite）=="
CUR=0
command -v node >/dev/null && CUR="$(node -e 'console.log(process.versions.node.split(".")[0])' 2>/dev/null || echo 0)"
if [ "$CUR" -lt "$NEED_NODE_MAJOR" ]; then
  echo "  当前 Node=$(command -v node >/dev/null && node --version || echo 无)，装 Node 24 LTS…"
  curl -fsSL https://deb.nodesource.com/setup_24.x | bash -
  apt-get install -y nodejs
fi
node --version

echo "== ② 目录与权限 =="
mkdir -p "$DATA_DIR"
chmod 700 "$DATA_DIR"
mkdir -p /var/backups/sci-auth && chmod 700 /var/backups/sci-auth

echo "== ③ 配置文件 $ENV_FILE =="
if [ -f "$ENV_FILE" ]; then
  echo "  已存在，不覆盖（要改就直接编辑它）"
else
  cp "$REPO_ROOT/deploy-auth/sci-auth.env.example" "$ENV_FILE"
  # 自动播种两把随机密钥，省得运维忘了设导致「管理台没开」「重启就全员掉线」
  ADMIN_PW="$(openssl rand -base64 24 | tr -d '/+=' | cut -c1-24)"
  KEY_SEC="$(openssl rand -base64 32)"
  sed -i "s|^ADMIN_PASSWORD=.*|ADMIN_PASSWORD=$ADMIN_PW|" "$ENV_FILE"
  sed -i "s|^KEY_SECRET=.*|KEY_SECRET=$KEY_SEC|" "$ENV_FILE"
  sed -i "s|^SKILLS_DIR=.*|SKILLS_DIR=$REPO_ROOT/.opencode/skills|" "$ENV_FILE"
  chmod 600 "$ENV_FILE"
  echo "  已生成，管理台口令："
  echo "      $ADMIN_PW"
  echo "  （只在这里显示这一次；之后看 $ENV_FILE）"
fi
chmod 600 "$ENV_FILE"
grep -q '^LLM_UPSTREAM_KEY=.\+' "$ENV_FILE" || \
  echo "  ⚠ 还没配 LLM_UPSTREAM_KEY —— /llm 会返回 503，客户端调不到模型。请编辑 $ENV_FILE" >&2

echo "== ④ systemd 单元 =="
sed "s|/root/sci-agent|$REPO_ROOT|g" "$REPO_ROOT/deploy-auth/sci-auth.service" > /etc/systemd/system/sci-auth.service
systemctl daemon-reload
systemctl enable sci-auth >/dev/null
echo "  已装 /etc/systemd/system/sci-auth.service"

echo "== ⑤ Caddy =="
if ! command -v caddy >/dev/null; then
  echo "  装 Caddy…"
  apt-get install -y debian-keyring debian-archive-keyring apt-transport-https curl
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list >/dev/null
  apt-get update && apt-get install -y caddy
fi
if [ -n "${DOMAIN:-}" ]; then
  if [ -f /etc/caddy/Caddyfile ] && ! grep -q '^# generated by sci-auth setup' /etc/caddy/Caddyfile; then
    cp -a /etc/caddy/Caddyfile "/etc/caddy/Caddyfile.bak-$(date +%Y%m%d-%H%M%S)"
    echo "  原 Caddyfile 已备份"
  fi
  { echo "# generated by sci-auth setup"; sed "s|example.duckdns.org|$DOMAIN|" "$REPO_ROOT/deploy-auth/Caddyfile.example"; } > /etc/caddy/Caddyfile
  caddy validate --config /etc/caddy/Caddyfile --adapter caddyfile >/dev/null && echo "  Caddyfile 已写并通过校验（域名 $DOMAIN）"
else
  echo "  （没给 DOMAIN，跳过写 Caddyfile；模板见 deploy-auth/Caddyfile.example）"
fi

echo "== ⑥ 每日备份（含影子恢复演练）=="
cat > /etc/cron.d/sci-auth-backup <<EOF
# 每天 3:30 导出并【自动做一次影子恢复演练】；演练不过会以非零码退出并留下 .UNVERIFIED
30 3 * * * root $REPO_ROOT/ops/migrate-export.sh >/var/log/sci-auth-backup.log 2>&1
# 保留 14 天
40 3 * * * root find /var/backups/sci-auth -name 'sci-auth-backup-*' -mtime +14 -delete
EOF
echo "  已装 /etc/cron.d/sci-auth-backup"

echo "== ⑦ 起服务并自检 =="
systemctl restart sci-auth
sleep 1.5
systemctl is-active --quiet sci-auth && echo "  sci-auth 已在跑" || { journalctl -u sci-auth -n 30 --no-pager; exit 1; }
DB_FILE="$DATA_DIR/sci.db" DATA_DIR="$DATA_DIR" SECRETS_FILE="$ENV_FILE" "$REPO_ROOT/ops/selftest.sh"

echo
echo "== 完成 =="
echo "  管理台： https://${DOMAIN:-<你的域名>}/admin"
echo "  日志：   journalctl -u sci-auth -f"
echo "  备份：   $REPO_ROOT/ops/migrate-export.sh"
echo
echo "  收尾务必确认："
echo "   · $ENV_FILE 里 LLM_UPSTREAM_KEY 已填"
echo "   · 云安全组只放行 22/80/443；8090 只听回环（不要放行）"
echo "   · SSH 已改密钥登录、关掉口令登录"
